### ISSUE TITLE
GEAR silently refuses to load some binaries

### ISSUE THREAD

**Issue by Wuerfel21** [davispuh/gear-emu#20]
The attached ZIP contains two binaries ([Spin Hexagon](https://github.com/IRQsome/Spin-Hexagon) and its bootloader):
- hexagon_boot.binary is accepted and displays the initial "Loading Spin Hexagon..." message when the TV plugin is loaded
- hexagon.binary does absolutely nothing at all - even if I load it while another binary is running, it just keeps on running that one

[gear_bug1.zip](https://github.com/davispuh/gear-emu/files/5147552/gear_bug1.zip)

**Comment by gatuno1** [comment]
Hello:
Please tell what version of Gear are you using. 
Few days ago I released a new version including patch "Correct video frame load timing, added video break, fix tab refresh", so maybe the new characteristics could be involved or can be used to debug it.

**Comment by Wuerfel21** [comment]
Oops, sorry about that, I indeed included the wrong files...
[gear_bug1.zip](https://github.com/davispuh/gear-emu/files/5151348/gear_bug1.zip)

I downloaded the latest release just yesterday, so yes, it's `GEAR_V20_08_01`

**Comment by gatuno1** [comment]
OK, don't worry. With the new files I can load "hexagon_boot.binary", seeing it run changing pins 12, 13 & 14 to manage TV. With Television plugin it show correctly, as you explain before.
Also, I can see this program are changing pins P20, P24 & P25. Please confirm if the latter is for communicate with SD card? Is the second binary supposed to reside there and is loaded by the first?
If it is the case, I'm sorry to tell you that already there is no mechanism or plugin to do this... 
That no means it could be developed, but I don't know how it could be emulated (are you waiting a standard SD format? Do you need a defined O.S.?).

**Comment by Wuerfel21** [comment]
The bootloader will of course try (and fail) to load the main program into RAM. I know that it can't do that without an SD plugin.

However, the main program does work without the bootloader (it just wont have any SD-related features). Well, "work". It'd need a keyboard or gamepad, but it should at least draw the title screen without anything connected. Whereas it currently doesn't even get loaded at all.

**Comment by gatuno1** [comment]
Well, I debug the second binary, and realized where the problem is: program size is bigger than total memory of P1 chip! hexagon.binary has 45196 bytes, and the real CPU has 32768.
This is validated on Gear to be accurate to emulate the real CPU, and don't continue the load. 
The real bug, is there isn't a message about the situation.
I can fix this one, but the lack of dynamic load from SD card is the feature you need, but we don't have already.

**Comment by Wuerfel21** [comment]
Oh yeah, I remember messing about with optimization settings and apparently accidentally overwrote the good binary (and because it's newer than the source files, the build script didn't rebuild it)

Yeah, an error message would be very helpful

**Comment by Wuerfel21** [comment]
Indeed, seems to work after recompiling

**Comment by gatuno1** [comment]
Yesterday I upload a patch for bug (commit fe5274fc31b432b31a405c44d4ce74693bc4d500), and now it shows a message on binaries bigger than P1 RAM.
