### ISSUE TITLE
Inaccuracy in Spin literal decoding

### ISSUE THREAD

**Issue by Wuerfel21** [davispuh/gear-emu#23]
When decoding opcode 0x37's argument, the actual interpreter uses a ROL instruction: https://github.com/parallaxinc/Propeller_1_Design/blob/499b248c62bf09191ff11ba5f762fd68d13151fd/interpreter.src#L539

GEAR uses a SHL, so if the shift amount is 31, it gets zero instead of one: 
https://github.com/davispuh/gear-emu/blob/c76aa434168acb0eb32a884c9870deefa483898d/Gear/EmulationCore/InterpretedCog.cs#L758

**Comment by gatuno1** [comment]
Thanks for the alert. Very clear your explanation, so I think it is easy to fix.

**Comment by gatuno1** [comment]
Well, it takes a little time to fix, but upload commit 2845f4c, to correct the bug.

Now it emulate a ROL pasm instruction:
https://github.com/davispuh/gear-emu/blob/2845f4c1b95896b2a83db95178ff6c5d924b2361/Gear/EmulationCore/InterpretedCog.cs#L758
