### ISSUE TITLE
Spin: math modify \w swapped registers is unhandled

### ISSUE THREAD

**Issue by Wuerfel21** [davispuh/gear-emu#24]
In a mem/register modify op, [there's a bit to swap the arguments of a binary math operator.](https://github.com/parallaxinc/Propeller_1_Design/blob/499b248c62bf09191ff11ba5f762fd68d13151fd/interpreter.src#L145)

It seems GEAR is unaware of this.

**Comment by Wuerfel21** [comment]
This isn't really documented much at all, outside of the interpreter source. And I don't think any compiler used it until I wrote the bytecode backend for flexspin.
 Basically, in the byte that specifies the operator for a modify instruction, if the operator is a binary operator (like add, sub, multiply), bit 5 will swap the operands. This allows doing a `x := 1 - x` kinda operation.

**Comment by Wuerfel21** [comment]
Here's an actual example: This code here...
```spin
CON
_CLKMODE = XTAL1+PLL16X
_XINFREQ = 5_000_000      
OBJ text : "TV_Text"                 
PUB main | i
i := 20
text.start(12)
i := 1 - i
text.dec(i)
```
compiled with openspin and `flexspin -O1 --interp=rom`. On real P1 both display `-19` on the TV, but on GEAR the flexspin binary fails and displays `0`

[tv_reversemod.zip](https://github.com/davispuh/gear-emu/files/6641195/tv_reversemod.zip)

**Comment by gatuno1** [comment]
I tryed to compile the source code with Propeller Tool v.1.3.2, and GEAR shows -19!


![Emulation-proptool](https://user-images.githubusercontent.com/8146845/121762111-e1491100-cb01-11eb-9f68-cc619fa49c1e.png)
![EmulationTV-proptool](https://user-images.githubusercontent.com/8146845/121762119-f45be100-cb01-11eb-9649-259896b81fa5.png)
[tv_reversemod.zip](https://github.com/davispuh/gear-emu/files/6641502/tv_reversemod.zip)

**Comment by Wuerfel21** [comment]
Oops, sorry , sent the wrong files

**Comment by Wuerfel21** [comment]
No, wait I did send the right files.That it works when compiled with Propeller Tool is obvious, but when compiled with flexspin it doesn't, that's why I attached the binary.

**Comment by gatuno1** [comment]
You are right. Now I realize the real problem: the spin packed code emitted by flexspin isn't emulated correctly by GEAR.
Could you show me the the difference between the two packed codes for the SUSTRACT operation?
Yesterday analized the GEAR code for math opcodes, and I realized the option to swap existed, but isn't activated when the opcode is executed. I would like to see the difference between them.

**Comment by Wuerfel21** [comment]
For `i:=1-i`, flexspin emits:
```
0025: 36                      ' CONSTANT 1
0026: 66 6D                   ' MEM_MODIFY LONG DBASE+$0004 (short) SUB (REVERSE)
```
For `i:=i-1` or `i-=1`, it emits:
```
0025: 36                      ' CONSTANT 1
0026: 66 4D                   ' MEM_MODIFY LONG DBASE+$0004 (short) SUB 
```
It's really just the one bit. I think the issue in GEAR is more than just not swapping the operands though (because that'd give +19)

**Comment by gatuno1** [comment]
I have been researching the available documentation on spinbytecode, and found a document by cluso99, (https://forums.parallax.com/discussion/comment/796018/#Comment_796018), showing the use of 2nd opcodes, at least with three cases:

1. op code $37 [special purpose ops] 
2. op codes $40-$7F [Fast access VAR, LOC]
3. op codes $80-$DF [Access MEM, OBJ, VAR and LOC]

For convenience, I generate a PDF file with that information: [Spin Bytecode Document RR20080721.pdf](https://github.com/davispuh/gear-emu/files/6643151/Spin.Bytecode.Document.RR20080721.pdf)

I don't understand two more cases, if they involve more cases that use 2nd opcodes, or if it is explained how they are used as 2nd opcodes:
a. Section 'Assignment Operators'
b. Section 'Address bytecodes'

As I can see in GEAR code, suspect it didn't manage second operations in range $60-$7F. I would try to add support for it, but as I don't know real use case, suspect I could broke already working code.

Can I ask you your help emiting code to test the three cases?

**Comment by Wuerfel21** [comment]
Just looked into it myelf and submitted a PR #25 . As said there, can't actually test it because the C# compiler refuses to install itself.

**Comment by gatuno1** [comment]
I'm testing your pull request. I made almost the same changes...

**Comment by gatuno1** [comment]
> compiled with openspin and flexspin -O1 --interp=rom. On real P1 both display -19 on the TV, but on GEAR the flexspin binary fails and displays 0

Sorry, but I can't get flexprop compile with '--interp=rom' option, on v5.5.0. 
What version or option do I need?
![imagen](https://user-images.githubusercontent.com/8146845/121820497-115af600-cc61-11eb-9093-662bb0eb2454.png)

**Comment by Wuerfel21** [comment]
You'll need to build flexspin from latest source, the bytecode backend is a very recent development

**Comment by gatuno1** [comment]
Ufff, I want to test this code:

    CON
    _CLKMODE = XTAL1+PLL16X
    _XINFREQ = 5_000_000      
    OBJ text : "TV_Text"                 
    PUB main | i
    text.start(12)
    
    i := 20
    text.str(string("i := "))
    text.dec(i)
    text.str(string("; i := 1 - i; i: "))
    i := 1 - i
    text.dec(i)
    
    i := 20
    text.str(string(13,"i := "))
    text.dec(i)
    text.str(string("; i := i - 1; i: "))
    i := i - 1
    text.dec(i)

**Comment by Wuerfel21** [comment]
Here's the latest commit, I just pulled it off the CI
[flexptools-git (11).zip](https://github.com/davispuh/gear-emu/files/6644580/flexptools-git.11.zip)

**Comment by gatuno1** [comment]
Thanks for the build!
The last code now it is working.  I'll test other cases too.

![flexprop_vs_proptool1](https://user-images.githubusercontent.com/8146845/121824055-42462580-cc77-11eb-9e3c-59c551c50ef7.jpg)

![flexprop_vs_proptool3](https://user-images.githubusercontent.com/8146845/121824064-51c56e80-cc77-11eb-96f9-10e600c8dc77.jpg)

**Comment by gatuno1** [comment]
I'll aprove the commit, then will include some changes: simplify code and documenting it.

**Comment by gatuno1** [comment]
I had publish a new Release v.20.06.01 with all the changes applyed.
I expect it will be useful for for your development with spin2cpp...
